name: release
on:
    workflow_dispatch:
        inputs:
            release_version:
                description: 'Version number for new release'
                required: true
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ 3.9 ]
        steps:
            -   uses: actions/checkout@v2
            -   name: set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: install dependencies
                run: |
                    python -m pip install --upgrade pip
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: build sdist bdist_wheel
                run: |
                    VERSION=${{ github.event.inputs.release_version }}
                    sed -i "s/version='.*'/version='$VERSION'/g" setup.py
                    git config user.name ${{ github.actor }}
                    git commit . -m "Bump version to ${VERSION}"
                    git push origin master
                    git tag $VERSION
                    git push origin $VERSION
                    python setup.py sdist bdist_wheel
            -   name: deploy on pypi
                uses: pypa/gh-action-pypi-publish@master
                with:
                    password: ${{ secrets.PYPI_API_TOKEN }}
